#we use java
language: java
#jdk
jdk:
 - openjdk8
#Linking Travis CI and Docker
 - docker
#linux_permissin for travis-ci
before_install:
  - chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
#deploying the app on docker
 - mvn deploy



